Ecommerce_Django_App/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm
from account import views
app_name = 'account'
urlpatterns = [
    path('send-otp', views.send_otp, name = 'send_otp'),
    path('verify-otp', views.verify_otp, name ='verify_otp'),
    path('create-account/', views.userCreationView, name='create_account' ),
    path('login/', auth_views.LoginView.as_view
    (template_name='user/login.html', authentication_form =CustomLoginForm ,next_page= 'home'), name= 'login' ),
    path('logout/', views.logoutView, name='logout'),
    
    path('admin-login/', auth_views.LoginView.as_view
    (template_name='super_admin/login.html', authentication_form =CustomLoginForm ,next_page= 'super_admin:home'), name= 'admin_login' ),
    path('admin-creation', views.AdminCreationView.as_view(), name='admin_creation'),
    path('admin-logout', views.adminLogoutView, name='admin_logout'),

]

Ecommerce_Django_App/appleshop/urls.py
# ================== appleshop URL Configuration ===============

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('super-admin/', include('super_admin.urls', namespace = 'super_admin')),
    path('', include('home.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('offers/', include('offers.urls', namespace='offers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls', namespace='products')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('account/', include('account.urls', namespace='account')),

    path('password-reset/', auth_views.PasswordResetView.as_view
    (template_name = 'user/password_reset.html', form_class = CustomPasswordResetForm), name = 'password_reset'),
    path('password-rest-done/', auth_views.PasswordResetDoneView.as_view
    (template_name = 'user/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
    (template_name = 'user/password_reset_confirm.html', form_class = CustomSetPasswordForm), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name = 'user/password_reset_complete.html'), name = 'password_reset_complete'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce_Django_App/cart/urls.py
from django.urls import path
from cart import views
app_name = 'cart'
urlpatterns = [
    
    path('', views.cartView, name = 'cart'),

    path('add-to-cart/', views.addToCartView, name= 'add_to_cart'),
    path('add-to-cart/<str:pk>/', views.addToCartBeforeLoginView, name= 'add_to_cart_brfore_login'),
    path('change-qty/', views.changeQtyView, name  = 'change_qty'),

]

Ecommerce_Django_App/home/urls.py
from django import views
from django.urls import path
from home import views

urlpatterns = [
    path('', views.homeView, name='home')
]

Ecommerce_Django_App/products/urls.py
from django.urls import path
from products import views
app_name = 'products'

urlpatterns = [
    path('product-list/<str:pk>/', views.productListView, name = 'product_list'),
    path('product-details/<str:pk>/', views.productDetailsView, name = 'product_details'),
]

Ecommerce_Django_App/profiles/urls.py
from django.urls import path
from profiles import views
app_name = 'profiles'
urlpatterns = [
    path('customer-profile/', views.CustomerProfileView.as_view(), name = 'customer_profile'),
    path('admin-profile/', views.AdminProfileView.as_view(), name = 'admin_profile'),
    path('address/', views.addressView, name = 'address'),
    path('address-delete/', views.addressDeleteView, name = 'address_delete'),
    path('address-edit/', views.addressEdit, name = 'address_edit'),
    path('address-default/', views.addressDefaultView, name = 'address_dafault'),
]

Ecommerce_Django_App/super_admin/urls.py
from django.urls import path
from super_admin import views

app_name = 'super_admin'
urlpatterns = [
    path('',views.homeView, name='home'),
    path('chart/',views.homeView, name='home'),

    path('category-add',views.CategoryAddView.as_view(), name='category_add'),
    path('category-list/', views.categoryListView, name= 'category_list'),
    path('category-details/<str:pk>', views.categoryDetailsView, name= 'category_details'),
    path('category-edit/<str:pk>', views.CategoryEditView.as_view(), name= 'category_edit'),
    path('category-delete/<str:pk>', views.categoryDeleteView, name= 'category_delete'),

    path('product-add',views.ProductAddView.as_view(), name='product_add'),
    path('product-list/', views.productListView, name= 'product_list'),
    path('product-details/<str:pk>', views.productDetailsView, name= 'product_details'),
    path('product-edit/<str:pk>', views.ProductEditView.as_view(), name= 'product_edit'),
    path('product-delete/<str:pk>', views.productDeleteView, name= 'product_delete'),

    path('coupon-add',views.couponAddView, name='coupon_add'),
    path('coupon-list/', views.couponListView, name= 'coupon_list'),
    path('coupon-edit/<str:pk>', views.CouponEditView.as_view(), name= 'coupon_edit'),
    path('coupon-delete/<str:pk>', views.couponDeleteView, name= 'coupon_delete'),

    path('order-list/', views.OrderListView.as_view(), name= 'order_list'),

    path('customer-list/', views.customerListView, name= 'customer_list'),
    path('admin-list/', views.adminListView, name= 'admin_list'),
    path('admin-request-list/', views.AdminRequestListView.as_view(), name= 'admin_request_list'),


]

Ecommerce_Django_App/profiles/models.py
from django.db import models
from account.models import CustomUser

STATE_CHOICES = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa','Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
    ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
    ('Chandigarh', 'Chandigarh'),
    ('Dadra & Nagar Haveli and Daman & Diu', 'Dadra & Nagar Haveli and Daman & Diu'),
    ('Delhi', 'Delhi'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Lakshadweep', 'Lakshadweep'),
    ('Puducherry', 'Puducherry'),
    ('Ladakh', 'Ladakh')
)


class CustomerAddress(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.TextField()
    state = models.CharField(max_length=100, choices=STATE_CHOICES)
    pin = models.PositiveIntegerField()
    mob = models.PositiveIntegerField()
    edit = models.BooleanField(default=False)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.name


   

Ecommerce_Django_App/super_admin/models.py
from django.db import models

# Create your models here.

Ecommerce_Django_App/account/forms.py
from django import forms
from account.models import CustomUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm,
PasswordResetForm, SetPasswordForm)





class CustomUserCreationForm(UserCreationForm):
    # username = forms.CharField(
    #     widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'User Name'}))
    # )
    # email = forms.CharField(
    #     widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : 'Email'})
    # )
    # mobile = forms.IntegerField(
    # widget=forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Mobile'})
    # )
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'})
    # )
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Confirm Password'})
    # )


    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'mobile', 'password1', 'password2', 'is_admin_request' )

class CustomLoginForm(AuthenticationForm):
    username = forms.IntegerField(
        widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Mobile Number'}),
        
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'})
    )


class CustomPasswordResetForm(PasswordResetForm):
        email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", "class" : "form-control"}),
    )

class CustomSetPasswordForm(SetPasswordForm):
        new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class" : "form-control"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
        new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class" : "form-control"}),
    )
        

Ecommerce_Django_App/home/views.py
from django.shortcuts import render
from category.models import Category
from products.models import Product


def homeView(request):
    categories = Category.objects.all().order_by('order_by')
    products_in_home = Product.objects.filter(is_visible_home_img = True).order_by('home_img_order')

    context = {
    'categories' : categories,
    'products_in_home' : products_in_home
    }
    return render(request, 'user/home.html', context)

Ecommerce_Django_App/profiles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views import View
from django.utils.decorators import method_decorator
from profiles.form import AddressForm, ProfileForm
from profiles.models import CustomerAddress 
from account.models import CustomUser

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class CustomerProfileView(View):
    
    def get(self, request):
        form = AddressForm
        user = CustomUser.objects.get(username = request.user.username)
        profiles_form = ProfileForm(instance= user)
        addresses = CustomerAddress.objects.filter(user = request.user).order_by('-default')
        context = {
            'addresses' : addresses,
            'form' : form,
            'profiles_form' : profiles_form
        }
        return render(request, 'user/profile.html', context)
    def post(self, request):
        profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:customer_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:coustomer_profile')

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class AdminProfileView(View):
    def get(self, request):
        profile_form = ProfileForm(instance= request.user)
        context = {
            'profile_form' : profile_form
        }
        return render(request, 'super_admin/profile.html', context)

    def post(self, request):
        user_profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if user_profile_form.is_valid():
            user_profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:admin_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:admin_profile')



@login_required(login_url='account:login')
def addressView(request):

    if request.method == 'POST':
        default_address = CustomerAddress.objects.filter(user = request.user, default = True)
        for address in default_address:
            address.default = False
            address.save()
        name = request.POST.get('name')
        address = request.POST.get('address')
        state = request.POST.get('state')
        pin = request.POST.get('pin')
        mob = request.POST.get('mob')

        try:
            edit_address = CustomerAddress.objects.get(edit = True)
            edit_address.name = name
            edit_address.address = address
            edit_address.state = state
            edit_address.pin = pin
            edit_address.mob = mob
            edit_address.edit = False
            edit_address.default = True
            edit_address.save()

            print('update')
        except:
            CustomerAddress.objects.create(
            user = request.user, 
            name = name, 
            address = address, 
            state = state, 
            pin = pin, 
            mob = mob, 
            default = True
            )
            data = { 
                'status' : 'Product added successfully'
            }
            print('create')
            return JsonResponse(data)
    
    form = AddressForm
    context = {'form' : form }
    return render(request, 'user/profile.html', context)

@login_required(login_url='account:login')
def addressDefaultView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        all_address = CustomerAddress.objects.filter(user = request.user)
        for address in all_address:
            address.default = False
            address.save()
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.default = True
        address.save()
        data = { 
            'status' : 'set to default'
        }
        return JsonResponse(data)

@login_required(login_url='account:login')
def addressDeleteView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.delete()
        data = { 
            'status' : 'Product added successfully'
        }
        return JsonResponse(data)


@login_required(login_url='account:login')
def addressEdit(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.edit = True
        address.save()
        data = {
            'name' : address.name,
            'address' : address.address,
            'state' : address.state,
            'pin' : address.pin,
            'mob' : address.mob
        }
        return JsonResponse(data)

Ecommerce_Django_App/templates/super_admin/category_add.html
{% extends 'super_admin/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% load crispy_forms_filters %}
{% block css%}
<style>
    .form-group {
        width: 50%;
        padding: 20px;
        float: left;
    }
</style>
{% endblock %}
{% block title %} Category add {% endblock title %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Category Details Form</h4>
                <div class="row">
                    <form action="" method="post" enctype="multipart/form-data">
                        <div class="row">
                            {% csrf_token %}
                            {{form | crispy}}
                        </div>

                        <div class="row">
                            <input class="btn btn-success d-block w-25 m-auto" type="submit" value="SAVE">

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Ecommerce_Django_App/templates/super_admin/category_list.html
{% extends 'super_admin/base.html' %}
{% load static %}
{% block title %} Category list {% endblock title %}

{% block content %}
<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Category List</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Category Name </th>
                                <th> trending </th>
                                <th> offer</th>
                                <th> Status </th>


                            </tr>
                        </thead>
                        <tbody>
                            {% for category in categorys %}
                            <tr>
                                <td>
                                    <a href="{% url 'super_admin:category_details' category.id %}">
                                        <img src="{{category.image.url}}" alt="image" />
                                        <span class="pl-2 text-capitalize">{{category.category}}</span>
                                    </a>
                                </td>
                                <td> {{category.trending}} </td>
                                <td> {{category.offfer}} </td>
                                <td>
                                    {% if category.status %}
                                    <div class="text-success">Show</div>
                                    {% else %}
                                    <div class="text-danger">Hidden</div>
                                    {% endif %}
                                </td>
                                <td><a href="{% url 'super_admin:category_edit' category.id %}"><i
                                            class="fa-solid fa-pen-to-square"></i></a></td>
                                <td>

                                    <!-- Button trigger modal -->
                                    <div type="button" class="" data-bs-toggle="modal"
                                        data-bs-target="#id{{category.id}}">
                                        <i class="fa-solid fa-trash text-danger"></i>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="id{{category.id}}" tabindex="-1"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Delete category</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure you want to delete the selected category?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Close</button>
                                                    <a href="{% url 'super_admin:category_delete' category.id %}"
                                                        type="button" class="btn btn-danger">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Ecommerce_Django_App/templates/super_admin/coupon_add.html
{% extends 'super_admin/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% load crispy_forms_filters %}
{% block css%}
<style>
    .form-group {
        width: 50%;
        padding: 20px;
        float: left;
    }
</style>
{% endblock %}
{% block title %} Coupon add {% endblock title %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Coupon Details Form</h4>
                <div class="row">
                    <form action="" method="post" enctype="multipart/form-data">
                        <div class="row">
                            {% csrf_token %}
                            {{form | crispy}}
                        </div>

                        <div class="row">
                            <input class="btn btn-success d-block w-25 m-auto" type="submit" value="SAVE">

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Ecommerce_Django_App/templates/super_admin/coupon_list.html
{% extends 'super_admin/base.html' %}
{% load static %}
{% block title %} Coupon list {% endblock title %}

{% block content %}
<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">coupon List</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Coupon Name </th>
                                <th> Coupon Code </th>
                                <th> Discount (Rs) </th>
                                <th> Redeem</th>
                                <th> Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for coupon in coupons %}
                            <tr>

                                <td> {{coupon.coupon_name}} </td>
                                <td> {{coupon.coupon_code}} </td>
                                <td> {{coupon.discount}} </td>
                                <td>
                                    {% if coupon.is_redeemed %}
                                    <div class="text-danger">Redeemed</div>
                                    {% else %}
                                    <div class="text-success">Not Redeemed</div>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if coupon.is_active %}
                                    <div class="text-success">Active</div>
                                    {% else %}
                                    <div class="text-danger">Not Active</div>
                                    {% endif %}
                                </td>
                                <td>
                                    <a a href="{% url 'super_admin:coupon_edit' coupon.id %}"><i
                                            class="fa-solid fa-pen-to-square"></i></a>
                                </td>
                                <td>

                                    <!-- Button trigger modal -->
                                    <div type="button" class="" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                        <i class="fa-solid fa-trash text-danger"></i>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Delete coupon</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure you want to delete the selected coupon?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Close</button>
                                                    <a href="{% url 'super_admin:coupon_delete' coupon.id %}"
                                                        type="button" class="btn btn-danger">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Ecommerce_Django_App/templates/super_admin/product_list.html
{% extends 'super_admin/base.html' %}
{% load static %}
{% block title %} Product list {% endblock title %}

{% block content %}
<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Product List</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Product Name </th>
                                <th> Category </th>
                                <th> Selling Price </th>
                                <th> Marking Price </th>
                                <th> Qty</th>
                                <th> Offer</th>
                                <th> Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                            <tr>

                                <td>
                                    <a href="{% url 'super_admin:product_details' product.id %}">
                                        <img src="{{product.image1.url}}" alt="image" />
                                        <span class="pl-2 text-capitalize">{{product.name}}</span>
                                    </a>
                                </td>
                                <td> {{product.category}} </td>
                                <td> {{product.selling_price}} </td>
                                <td> {{product.marking_price}} </td>
                                <td> {{product.qty}} </td>
                                <td> {{product.offer}} </td>
                                <td>
                                    {% if product.status %}
                                    <div class="text-success">Show</div>
                                    {% else %}
                                    <div class="text-danger">Hidden</div>
                                    {% endif %}
                                </td>
                                <td><a href="{% url 'super_admin:product_edit' product.id %}"><i
                                            class="fa-solid fa-pen-to-square"></i></a></td>
                                <td>

                                    <!-- Button trigger modal -->
                                    <div type="button" class="" data-bs-toggle="modal"
                                        data-bs-target="#id{{product.id}}">
                                        <i class="fa-solid fa-trash text-danger"></i>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="id{{product.id}}" tabindex="-1"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Delete Product</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure you want to delete the selected product?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Close</button>
                                                    <a href="{% url 'super_admin:product_delete' product.id %}"
                                                        type="button" class="btn btn-danger">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}