Ecommerce_Django_App/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm
from account import views
app_name = 'account'
urlpatterns = [
    path('send-otp', views.send_otp, name = 'send_otp'),
    path('verify-otp', views.verify_otp, name ='verify_otp'),
    path('create-account/', views.userCreationView, name='create_account' ),
    path('login/', auth_views.LoginView.as_view
    (template_name='user/login.html', authentication_form =CustomLoginForm ,next_page= 'home'), name= 'login' ),
    path('logout/', views.logoutView, name='logout'),
    
    path('admin-login/', auth_views.LoginView.as_view
    (template_name='super_admin/login.html', authentication_form =CustomLoginForm ,next_page= 'super_admin:home'), name= 'admin_login' ),
    path('admin-creation', views.AdminCreationView.as_view(), name='admin_creation'),
    path('admin-logout', views.adminLogoutView, name='admin_logout'),

]

Ecommerce_Django_App/appleshop/urls.py
# ================== appleshop URL Configuration ===============

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('super-admin/', include('super_admin.urls', namespace = 'super_admin')),
    path('', include('home.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('offers/', include('offers.urls', namespace='offers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls', namespace='products')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('account/', include('account.urls', namespace='account')),

    path('password-reset/', auth_views.PasswordResetView.as_view
    (template_name = 'user/password_reset.html', form_class = CustomPasswordResetForm), name = 'password_reset'),
    path('password-rest-done/', auth_views.PasswordResetDoneView.as_view
    (template_name = 'user/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
    (template_name = 'user/password_reset_confirm.html', form_class = CustomSetPasswordForm), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name = 'user/password_reset_complete.html'), name = 'password_reset_complete'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce_Django_App/cart/urls.py
from django.urls import path
from cart import views
app_name = 'cart'
urlpatterns = [
    
    path('', views.cartView, name = 'cart'),

    path('add-to-cart/', views.addToCartView, name= 'add_to_cart'),
    path('add-to-cart/<str:pk>/', views.addToCartBeforeLoginView, name= 'add_to_cart_brfore_login'),
    path('change-qty/', views.changeQtyView, name  = 'change_qty'),

]

Ecommerce_Django_App/home/urls.py
from django import views
from django.urls import path
from home import views

urlpatterns = [
    path('', views.homeView, name='home')
]

Ecommerce_Django_App/orders/urls.py
from django.urls import path
from orders import views
app_name = 'orders'
urlpatterns = [
    path('single-order/<str:pk>/', views.singleOrderView, name = 'single_order'),
    path('cart-order/', views.cartOrderView, name = 'cart_order'),
    path('your-order/', views.yourOrderView, name = 'your_order'),

    path('payment', views.paymentView),
    path('razorpay/', views.razorpayKey)

]

Ecommerce_Django_App/products/urls.py
from django.urls import path
from products import views
app_name = 'products'

urlpatterns = [
    path('product-list/<str:pk>/', views.productListView, name = 'product_list'),
    path('product-details/<str:pk>/', views.productDetailsView, name = 'product_details'),
]

Ecommerce_Django_App/profiles/urls.py
from django.urls import path
from profiles import views
app_name = 'profiles'
urlpatterns = [
    path('customer-profile/', views.CustomerProfileView.as_view(), name = 'customer_profile'),
    path('admin-profile/', views.AdminProfileView.as_view(), name = 'admin_profile'),
    path('address/', views.addressView, name = 'address'),
    path('address-delete/', views.addressDeleteView, name = 'address_delete'),
    path('address-edit/', views.addressEdit, name = 'address_edit'),
    path('address-default/', views.addressDefaultView, name = 'address_dafault'),
]

Ecommerce_Django_App/cart/models.py
from django.db import models
from account.models import CustomUser
from products.models import Product

class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='u_cart')
    product = models.ForeignKey(Product, on_delete=models.CASCADE )
    qty = models.PositiveIntegerField(default=1 )

    def __str__(self):

        return self.product.name

    def totalPrice(self):
        total_price = self.product.selling_price * self.qty
        return int(total_price)

Ecommerce_Django_App/profiles/models.py
from django.db import models
from account.models import CustomUser

STATE_CHOICES = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa','Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
    ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
    ('Chandigarh', 'Chandigarh'),
    ('Dadra & Nagar Haveli and Daman & Diu', 'Dadra & Nagar Haveli and Daman & Diu'),
    ('Delhi', 'Delhi'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Lakshadweep', 'Lakshadweep'),
    ('Puducherry', 'Puducherry'),
    ('Ladakh', 'Ladakh')
)


class CustomerAddress(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.TextField()
    state = models.CharField(max_length=100, choices=STATE_CHOICES)
    pin = models.PositiveIntegerField()
    mob = models.PositiveIntegerField()
    edit = models.BooleanField(default=False)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.name


   

Ecommerce_Django_App/account/forms.py
from django import forms
from account.models import CustomUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm,
PasswordResetForm, SetPasswordForm)





class CustomUserCreationForm(UserCreationForm):
    # username = forms.CharField(
    #     widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'User Name'}))
    # )
    # email = forms.CharField(
    #     widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : 'Email'})
    # )
    # mobile = forms.IntegerField(
    # widget=forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Mobile'})
    # )
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'})
    # )
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Confirm Password'})
    # )


    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'mobile', 'password1', 'password2', 'is_admin_request' )

class CustomLoginForm(AuthenticationForm):
    username = forms.IntegerField(
        widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Mobile Number'}),
        
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'})
    )


class CustomPasswordResetForm(PasswordResetForm):
        email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", "class" : "form-control"}),
    )

class CustomSetPasswordForm(SetPasswordForm):
        new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class" : "form-control"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
        new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class" : "form-control"}),
    )
        

Ecommerce_Django_App/cart/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from products.models import Product
from cart.models import Cart


@login_required(login_url='account:login')
def addToCartView(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        product = Product.objects.get(id = product_id)
        Cart.objects.create(user = request.user, product = product)
        data = { 
            'status' : 'Product added successfully'
        }
        return JsonResponse(data)

@login_required(login_url='account:login')
def addToCartBeforeLoginView(request, pk):
    product = Product.objects.get(id = pk)
    cart = Cart.objects.filter(product = product, user = request.user)
    if cart:
        return redirect('products:product_details', pk=str(pk))
    else:
        Cart.objects.create(user = request.user, product = product)
        return redirect('products:product_details', pk=str(pk))

@login_required(login_url='account:login')
def cartView(request):
    # =========== product revove from cart =============
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        cart_product = Cart.objects.get(user = request.user, product = product_id)
        cart_product.delete()
        return JsonResponse({'status' : 'Product removed from cart'})

    carts = Cart.objects.filter(user = request.user)
    no_of_items = carts.count()
    total_marking_price =0
    total_amount = 0
    for cart in carts:
        total_marking_price += cart.product.marking_price * cart.qty
        total_amount = total_amount + (cart.product.selling_price * cart.qty)
    discount = total_marking_price - total_amount
    cart = Cart.objects.filter(user = request.user)

    context = {
    'cart' : cart,
    'no_of_items' : no_of_items,
    'total_marking_price' : total_marking_price,
    'discount' : discount,
    'total_amount' : total_amount,
    }

    return render (request, 'user/cart.html', context)

def changeQtyView(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        qty = request.POST.get('quantity')
        cart = Cart.objects.get(user = request.user, product = product_id)
        cart.qty = qty
        cart.save()
        return JsonResponse({'status' : 'qty changed successfully'})

Ecommerce_Django_App/home/views.py
from django.shortcuts import render
from category.models import Category
from products.models import Product


def homeView(request):
    categories = Category.objects.all().order_by('order_by')
    products_in_home = Product.objects.filter(is_visible_home_img = True).order_by('home_img_order')

    context = {
    'categories' : categories,
    'products_in_home' : products_in_home
    }
    return render(request, 'user/home.html', context)

Ecommerce_Django_App/profiles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views import View
from django.utils.decorators import method_decorator
from profiles.form import AddressForm, ProfileForm
from profiles.models import CustomerAddress 
from account.models import CustomUser

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class CustomerProfileView(View):
    
    def get(self, request):
        form = AddressForm
        user = CustomUser.objects.get(username = request.user.username)
        profiles_form = ProfileForm(instance= user)
        addresses = CustomerAddress.objects.filter(user = request.user).order_by('-default')
        context = {
            'addresses' : addresses,
            'form' : form,
            'profiles_form' : profiles_form
        }
        return render(request, 'user/profile.html', context)
    def post(self, request):
        profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:customer_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:coustomer_profile')

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class AdminProfileView(View):
    def get(self, request):
        profile_form = ProfileForm(instance= request.user)
        context = {
            'profile_form' : profile_form
        }
        return render(request, 'super_admin/profile.html', context)

    def post(self, request):
        user_profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if user_profile_form.is_valid():
            user_profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:admin_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:admin_profile')



@login_required(login_url='account:login')
def addressView(request):

    if request.method == 'POST':
        default_address = CustomerAddress.objects.filter(user = request.user, default = True)
        for address in default_address:
            address.default = False
            address.save()
        name = request.POST.get('name')
        address = request.POST.get('address')
        state = request.POST.get('state')
        pin = request.POST.get('pin')
        mob = request.POST.get('mob')

        try:
            edit_address = CustomerAddress.objects.get(edit = True)
            edit_address.name = name
            edit_address.address = address
            edit_address.state = state
            edit_address.pin = pin
            edit_address.mob = mob
            edit_address.edit = False
            edit_address.default = True
            edit_address.save()

            print('update')
        except:
            CustomerAddress.objects.create(
            user = request.user, 
            name = name, 
            address = address, 
            state = state, 
            pin = pin, 
            mob = mob, 
            default = True
            )
            data = { 
                'status' : 'Product added successfully'
            }
            print('create')
            return JsonResponse(data)
    
    form = AddressForm
    context = {'form' : form }
    return render(request, 'user/profile.html', context)

@login_required(login_url='account:login')
def addressDefaultView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        all_address = CustomerAddress.objects.filter(user = request.user)
        for address in all_address:
            address.default = False
            address.save()
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.default = True
        address.save()
        data = { 
            'status' : 'set to default'
        }
        return JsonResponse(data)

@login_required(login_url='account:login')
def addressDeleteView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.delete()
        data = { 
            'status' : 'Product added successfully'
        }
        return JsonResponse(data)


@login_required(login_url='account:login')
def addressEdit(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.edit = True
        address.save()
        data = {
            'name' : address.name,
            'address' : address.address,
            'state' : address.state,
            'pin' : address.pin,
            'mob' : address.mob
        }
        return JsonResponse(data)

Ecommerce_Django_App/templates/user/cart.html
{% extends 'user/base.html' %}
{% block title %} Cart {% endblock title %}
{% block content %}

<div class="container p-0 ">
    <div class="refresh_cart row">
        <div class=" col-md-8">
            <div class=" shadow my-lg-3 p-lg-5 bg-body rounded">

                {% if cart %}
                <div class="container-fluid ">

                    {% for cart in cart %}
                    <div class="row py-5 position-relative">
                        <div class="col-4 ">
                            <img src="{{cart.product.image1.url}}" class="w-100" alt="">
                        </div>
                        <div class="closest_cls cart_prod_detail  col-8 p-0 ps-5 ">
                            <h5>{{cart.product.name}}</h5>
                            <h4 class="d-inline text-primary">₹{{cart.product.selling_price | stringformat:'d'}}</h4>
                            <h6 class="text-muted text-decoration-line-through d-inline">
                                ₹{{cart.product.marking_price | stringformat:'d'}}
                            </h6>
                            <h5 class="text-success">Total ₹{{cart.totalPrice | stringformat:'d'}}</h5>
                            {% csrf_token %}
                            <div class="qty_cart input-group w-100 d-flex">
                                <div class="qty_btn d-flex mt-3 w-50">
                                    <i class="minus_btn cursor_pointer fa-solid fa-circle-minus fs-1 text-danger"></i>
                                    <div>
                                        <input disabled class="button qty_input form-control text-center mx-3 p-0"
                                            id="qty" type="text" name="qty" value="{{cart.qty}}">
                                    </div>
                                    <i class="plus_btn cursor_pointer fa-solid fa-circle-plus fs-1 text-success"></i>
                                    <i
                                        class="dlt_btn cursor_pointer fa-solid fa-trash fs-1 ms-3 ms-lg-5 text-secondary"></i>
                                    <input type="hidden" class="product_id" value="{{cart.product.id}}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    {% endfor %}

                </div>
                {% else %}

                <h1 class="text-center text-warning p-5">No items in cart</h1>
                {% endif %}

            </div>
        </div>
        <div class="col-md-4">
            <div class="row shadow p-md-3 mt-md-3 ms-md-3 bg-body rounded">
                <div class="d-none d-md-block">
                    <h4>PRICE DETAILS</h4>
                    <hr>
                </div>
                <div class="col-8 d-none d-md-block">
                    <p>Price ({{no_of_items}} {% if no_of_items > 1 %} items {% else %} item {% endif%})</p>
                    <p>Discount</p>
                    <p>Delivery Charges</p>
                    <hr>
                    <h4>Total Amount</h4>
                </div>
                <div class="col-4 text-end d-none d-md-block">
                    <p>₹{{total_marking_price | stringformat:'d'}}</p>
                    <p class="text-danger">-₹{{discount | stringformat:'d'}}</p>
                    <p class="text-decoration-line-through">₹40</p>
                    <hr>
                    <h4 class="text-success">₹{{total_amount | stringformat:'d'}}</h4>
                </div>
                <div class="place_order">

                    {% if no_of_items %}
                    <a href="{% url 'orders:cart_order' %}"><button class="btn btn-success p-2 fs-5  w-100">
                            CHECKOUT <span class="d-md-none ps-3">₹ {{total_amount | stringformat:'d'}}</span>
                        </button></a>
                    {% else %}

                    <a href="{% url 'home' %}"><button class="btn btn-warning w-100">BACK TO HOME</button></a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Ecommerce_Django_App/templates/user/home.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %} Home {% endblock title %}
{% block content %}

<!-- ================slider=====================  -->

<header>
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators .text-muted">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3"
        aria-label="Slide 4"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active carousel1">
        <div class="carousel-caption d-none d-md-block">
          <h5></h5>
          <p></p>
        </div>
      </div>
      <div class="carousel-item carousel2">
        <div class="carousel-caption d-none d-md-block">
          <h5></h5>
          <h3>Light. Bright. Full of might</h3>
        </div>
      </div>
      <div class="carousel-item carousel3">
        <div class="carousel-caption d-none d-md-block">
          <h5>You’ve never heard colour like this.</h5>
          <p>Made to fill every room with rich, 360‑degree audio. Now available in five colours.</p>
        </div>
      </div>
      <div class="carousel-item carousel4">
        <div class="carousel-caption d-none d-md-block">
          <h5>Oh.So.Pro</h5>
          <p></p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="text-secondary fs-1">
        <i class="fa fa-angle-left" aria-hidden="true"></i>
      </span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="text-secondary fs-1">
        <i class="fa fa-angle-right" aria-hidden="true"></i>
      </span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</header>

<!-- ====================category================ -->

<div class="container p-lg-5">
  <div class="row products_category">
    {% for category in categories %}
    <div class="col-lg-2 col-4 mt-3">
      <a href="{% url 'products:product_list' category.category %}">
        <img class="items" src="{{category.image.url}}" alt="" w-100 />
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<!-- ========== home images =========== -->
<div class="home_products">
  {% for product in products_in_home %}
  {% if product.home_img %}
  <div class="row pt-5">
    <div class="col-12 text-center">
      <a href="{% url 'products:product_details' product.id %}" class="">
        <img src="{{product.home_img.url}}" class="home_img rounded-pill" style="max-width: 100%;">
      </a>
    </div>
  </div>

  {% endif %}
  {% endfor %}
</div>

{% endblock %}

Ecommerce_Django_App/templates/user/login.html
{% extends 'user/base.html' %}
{% block title %} Login {% endblock title %}
{% block content %}

<div class="container my-lg-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <h3>Login</h3>
                <hr>

                {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %} {% endif %}

                <form action="" method="post">
                    {% csrf_token %}

                    {% for form in form %}
                    <div class="form-group my-4">
                        {{form}}
                        <small class="text-danger">{{form.errors|striptags }}</small>
                    </div>
                    {% endfor %}

                    <div class="row mt-3">
                        <div class="col-lg-6 p-lg-3  ">
                            <button class="btn btn-warning px-5  me-auto fw-bold w-100">LOGIN</button>
                        </div>
                        <div class="col-lg-6 p-lg-3 mt-3 mt-lg-0">
                            <a class="btn btn-primary px-5  fw-bold w-100" href="{% url 'account:send_otp' %}">
                                SIGNUP
                            </a>
                        </div>
                    </div>
                    <a class="text-decoration-none" href="{% url 'password_reset' %}">
                        <p class="text-primary text-center m-3 fw-bold"> Forgot Password ?</p>
                    </a>

                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Ecommerce_Django_App/templates/user/password_reset.html
{% extends 'user/base.html' %}
{% block title %} Password Rest {% endblock title %}
{% block content %}

<div class="container my-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <h3>Password Reset</h3>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group my-4">
                        {{form}}
                        <span class="text-danger">{{form.errors | striptags }}</span>
                    </div>
                    <p class="text-secondary">Generate a one-use only link for resetting password and send it to the
                        user email.</p>
                    <button class="btn btn-warning px-5 mt-5 fw-bold d-block mx-auto">SEND</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Ecommerce_Django_App/templates/user/password_reset_complete.html
{% extends 'user/base.html' %}
{% block title %} Password Rest {% endblock title %}
{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-9 offset-sm-1 text-center shadow p-5">
            <h3 class="text-success">Password Reset Successfully</h3>
            <a href="{% url 'account:login' %}">Login to continue</a>
        </div>
    </div>
</div>

{% endblock content %}

Ecommerce_Django_App/templates/user/password_reset_confirm.html
{% extends 'user/base.html' %}
{% block title %} Password Rest {% endblock title %}
{% block content %}

<div class="container">
  <div class="row my-3">
    <div class="col-sm-6 offset-sm-3">
      <h3>Reset Your Password</h3>
      <hr />
      <form action="" method="post" novalidate class="shadow p-5">

        {% csrf_token %} {% for form in form%}
        <div class="form-group">
          {{form.label_tag}} {{form}}
          <small class="text-danger"> {{form.errors|striptags}} </small>
          <br />
        </div>

        {% endfor %}

        <input type="submit" class="btn btn-warning mt-4 d-block mx-auto" value="SUBMIT" />

        {% if form.non_field_errors %} {% for error in form.non_field_errors %}

        <p class="alert alert-danger my-3">{{error}}</p>

        {% endfor %} {% endif %}

      </form>
    </div>
  </div>
</div>

{% endblock content %}

Ecommerce_Django_App/templates/user/user_creation.html
{% extends 'user/base.html' %}
{% block title %} Signup {% endblock title %}
{% block content %}

<div class="container my-lg-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <h3 class="my-3 text-center">User Creation Form</h3>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group my-4">
                        <input type="hidden" name="mobile" maxlength="10" class="form-control" value="{{mobile}}"
                            placeholder="Enter Mobile" autofocus="" required="" id="id_mobile">
                        <small class="text-danger"></small>
                    </div>
                    <div class="form-group my-4">
                        <input type="text" name="username" class="form-control" placeholder="User Name" required=""
                            id="id_username">
                        <small class="text-danger">{{ form.username.errors }}</small>
                    </div>
                    <div class="form-group my-4">
                        <input type="email" name="email" class="form-control" placeholder="Email" required=""
                            id="id_email">
                        <small class="text-danger">{{ form.email.errors }}</small>
                    </div>
                    <div class="form-group my-4">
                        <input type="password" name="password1" class="form-control" placeholder="Password" required=""
                            id="id_password1">
                        <small class="text-danger">{{ form.password1.errors }}</small>
                    </div>
                    <div class="form-group my-4">
                        <input type="password" name="password2" class="form-control" placeholder="Confirm Password"
                            required="" id="id_password2">
                        <small class="text-danger">{{ form.password2.errors | striptags }}</small>
                    </div>
                    <button class="btn btn-warning fw-bold fs-5 px-5 mt-5 d-grid mx-auto">REGISTER</button>
                    <a href="/account/login/">
                        <p class="text-primary text-center fw-bold m-3"> Existing User? Log in</p>
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}